-- Seed all 349 menu items across 9 categories into public.products
truncate table public.products;

insert into public.products (name, price, category, sort_order, is_visible) values
  ('Baked Rasogolla 4pcs', 80.0::numeric, 'SWEETS', 1, true),
  ('Baked Rasogolla 1 Ps', 25.0::numeric, 'SWEETS', 2, true),
  ('Rasogolla', 15.0::numeric, 'SWEETS', 3, true),
  ('Golapjam', 25.0::numeric, 'SWEETS', 4, true),
  ('Pantooa', 15.0::numeric, 'SWEETS', 5, true),
  ('Langcha', 15.0::numeric, 'SWEETS', 6, true),
  ('Baked Mishti Dahi Cup', 90.0::numeric, 'SWEETS', 7, true),
  ('Talsans Big', 30.0::numeric, 'SWEETS', 8, true),
  ('Talsans Small', 20.0::numeric, 'SWEETS', 9, true),
  ('Ghee Soan Papri 250 Gm', 125.0::numeric, 'SWEETS', 10, true),
  ('Laddu', 15.0::numeric, 'SWEETS', 11, true),
  ('Sankha Sandesh', 15.0::numeric, 'SWEETS', 12, true),
  ('Malai Roll', 25.0::numeric, 'SWEETS', 13, true),
  ('Kheer Cham Cham', 15.0::numeric, 'SWEETS', 14, true),
  ('Kheer Gaja', 18.0::numeric, 'SWEETS', 15, true),
  ('Mathura Peda', 20.0::numeric, 'SWEETS', 16, true),
  ('Kalojam', 15.0::numeric, 'SWEETS', 17, true),
  ('Mihidana', 350.0::numeric, 'SWEETS', 18, true),
  ('Sitabhogh', 350.0::numeric, 'SWEETS', 19, true),
  ('Baked Sandwich', 25.0::numeric, 'SWEETS', 20, true),
  ('Paneer 200 Gm', 110.0::numeric, 'SWEETS', 21, true),
  ('Chitrakut', 15.0::numeric, 'SWEETS', 22, true),
  ('Mousumi Bhogh', 20.0::numeric, 'SWEETS', 23, true),
  ('Kesar Malai', 20.0::numeric, 'SWEETS', 24, true),
  ('Channa Payesh', 18.0::numeric, 'SWEETS', 25, true),
  ('Two In One Sandesh', 20.0::numeric, 'SWEETS', 26, true),
  ('Nauka Bilas', 15.0::numeric, 'SWEETS', 27, true),
  ('Kheer Kadam', 15.0::numeric, 'SWEETS', 28, true),
  ('Ross Kamal', 25.0::numeric, 'SWEETS', 29, true),
  ('Malai Chap', 25.0::numeric, 'SWEETS', 30, true),
  ('Kesar Peda', 18.0::numeric, 'SWEETS', 31, true),
  ('Gopal Bhog', 15.0::numeric, 'SWEETS', 32, true),
  ('Sweet Heart', 15.0::numeric, 'SWEETS', 33, true),
  ('Shanti Bhogh', 15.0::numeric, 'SWEETS', 34, true),
  ('Malai Kari', 18.0::numeric, 'SWEETS', 35, true),
  ('Patisapta Roll', 35.0::numeric, 'SWEETS', 36, true),
  ('Badshahi Roll', 18.0::numeric, 'SWEETS', 37, true),
  ('Kheer Biscuit', 20.0::numeric, 'SWEETS', 38, true),
  ('Shankha Bati', 20.0::numeric, 'SWEETS', 39, true),
  ('Swornim Special', 15.0::numeric, 'SWEETS', 40, true),
  ('Misti Dahi 100g', 25.0::numeric, 'SWEETS', 41, true),
  ('Misti Dahi 200g', 45.0::numeric, 'SWEETS', 42, true),
  ('Darbesh', 15.0::numeric, 'SWEETS', 43, true),
  ('Milk Cake', 15.0::numeric, 'SWEETS', 44, true),
  ('Kalakand', 15.0::numeric, 'SWEETS', 45, true),
  ('Gur Rasogolla', 15.0::numeric, 'SWEETS', 46, true),
  ('Cream Sandesh', 15.0::numeric, 'SWEETS', 47, true),
  ('Chocolate Ball', 20.0::numeric, 'SWEETS', 48, true),
  ('Gawa Ghee 200 Ml', 210.0::numeric, 'SWEETS', 49, true),
  ('Channa Ball', 10.0::numeric, 'SWEETS', 50, true),
  ('Khejur Burfi', 15.0::numeric, 'SWEETS', 51, true),
  ('Double Decker Sandesh', 18.0::numeric, 'SWEETS', 52, true),
  ('Swornim Sandesh', 15.0::numeric, 'SWEETS', 53, true),
  ('White Sandesh', 15.0::numeric, 'SWEETS', 54, true),
  ('Butter Scotch Sandesh', 15.0::numeric, 'SWEETS', 55, true),
  ('Motipak Burfi', 18.0::numeric, 'SWEETS', 56, true),
  ('Chocolate Matka', 20.0::numeric, 'SWEETS', 57, true),
  ('Chana Cocktail', 10.0::numeric, 'SWEETS', 58, true),
  ('Chocolate Chana Ball', 15.0::numeric, 'SWEETS', 59, true),
  ('Rossmadhuri', 20.0::numeric, 'SWEETS', 60, true),
  ('Tota Barfi', 15.0::numeric, 'SWEETS', 61, true),
  ('Sor Bhaja', 15.0::numeric, 'SWEETS', 62, true),
  ('Kanchagolla', 18.0::numeric, 'SWEETS', 63, true),
  ('Baked Tota Barfi', 20.0::numeric, 'SWEETS', 64, true),
  ('Baked Kalakand', 18.0::numeric, 'SWEETS', 65, true),
  ('Baked Malai Patties', 24.0::numeric, 'SWEETS', 66, true),
  ('Cream Chamcham', 20.0::numeric, 'SWEETS', 67, true),
  ('Channar Jilepi', 18.0::numeric, 'SWEETS', 68, true),
  ('Channa Toast', 15.0::numeric, 'SWEETS', 69, true),
  ('Mouchak', 15.0::numeric, 'SWEETS', 70, true),
  ('Cream Sandwich', 24.0::numeric, 'SWEETS', 71, true),
  ('Rasomalai', 25.0::numeric, 'SWEETS', 72, true),
  ('White Gujiya', 3.33::numeric, 'SWEETS', 73, true),
  ('Chandrakala', 15.0::numeric, 'SWEETS', 74, true),
  ('Gujiya', 12.0::numeric, 'SWEETS', 75, true),
  ('Kheer Potol', 25.0::numeric, 'SWEETS', 76, true),
  ('Chocolate Patties', 10.0::numeric, 'SWEETS', 77, true),
  ('Ros Kodom', 12.0::numeric, 'SWEETS', 78, true),
  ('Channa Paturi', 25.0::numeric, 'SWEETS', 79, true),
  ('Chau Kalakand', 12.0::numeric, 'SWEETS', 80, true),
  ('Abar Khabo', 20.0::numeric, 'SWEETS', 81, true),
  ('Cake Sandesh', 15.0::numeric, 'SWEETS', 82, true),
  ('Kesar Bhogh', 18.0::numeric, 'SWEETS', 83, true),
  ('Gajor Sandesh', 15.0::numeric, 'SWEETS', 84, true),
  ('Khaja', 15.0::numeric, 'SWEETS', 85, true),
  ('Badshahi Bhog', 12.0::numeric, 'SWEETS', 86, true),
  ('Cinnamon Sandesh', 15.0::numeric, 'SWEETS', 87, true),
  ('Plain Curd 100gm', 22.0::numeric, 'SWEETS', 88, true),
  ('Kheer Chop', 20.0::numeric, 'SWEETS', 89, true),
  ('Mini Gaja', 300.0::numeric, 'SWEETS', 90, true),
  ('Sugar Free Sandesh', 15.0::numeric, 'SWEETS', 91, true),
  ('Channa Cake', 15.0::numeric, 'SWEETS', 92, true),
  ('Aamsotto Sandesh Roll', 15.0::numeric, 'SWEETS', 93, true),
  ('Aamsotto Sandesh Cake', 15.0::numeric, 'SWEETS', 94, true),
  ('Mango Kalakand', 10.0::numeric, 'SWEETS', 95, true),
  ('Aamsatto Kalakand', 10.0::numeric, 'SWEETS', 96, true),
  ('Kancha Aam Rasogolla', 18.0::numeric, 'SWEETS', 97, true),
  ('Kesar Rasomalai', 25.0::numeric, 'SWEETS', 98, true),
  ('Kamalabhogh', 18.0::numeric, 'SWEETS', 99, true),
  ('Gawa Ghee 250ml', 310.0::numeric, 'SWEETS', 100, true),
  ('Channa Pora', 700.0::numeric, 'SWEETS', 101, true),
  ('Aam Kheer', 40.0::numeric, 'SWEETS', 102, true),
  ('Kancha Pak Sandesh', 18.0::numeric, 'SWEETS', 103, true),
  ('Baked Channa', 18.0::numeric, 'SWEETS', 104, true),
  ('Baked Mihidana Slice', 30.0::numeric, 'SWEETS', 105, true),
  ('Manohara', 25.0::numeric, 'SWEETS', 106, true),
  ('Channa Delight', 20.0::numeric, 'SWEETS', 107, true),
  ('Kaju Roll', 20.0::numeric, 'SWEETS', 108, true),
  ('Kheer Cake', 15.0::numeric, 'SWEETS', 109, true),
  ('Sour Curd', 90.0::numeric, 'SWEETS', 110, true),
  ('Loose Bonde', 350.0::numeric, 'SWEETS', 111, true),
  ('Malpoa With Rabri', 20.0::numeric, 'SWEETS', 112, true),
  ('Nikuti', 250.0::numeric, 'SWEETS', 113, true),
  ('Round Sandesh', 600.0::numeric, 'SWEETS', 114, true),
  ('Jilapi', 250.0::numeric, 'SWEETS', 115, true),
  ('Mohon Bhogh', 25.0::numeric, 'SWEETS', 116, true),
  ('Roll Chamcham', 18.0::numeric, 'SWEETS', 117, true),
  ('Malai Julie', 15.0::numeric, 'SWEETS', 118, true),
  ('Boibhashik Sandesh', 600.0::numeric, 'SWEETS', 119, true),
  ('Shahi Samosa', 30.0::numeric, 'SWEETS', 120, true),
  ('Mango Lassi', 30.0::numeric, 'SWEETS', 121, true),
  ('Rose Lassi', 30.0::numeric, 'SWEETS', 122, true),
  ('Baked Malai Chop', 15.0::numeric, 'SWEETS', 123, true),
  ('Malai Cham Cham', 20.0::numeric, 'SWEETS', 124, true),
  ('Malai Chamcham', 20.0::numeric, 'SWEETS', 125, true),
  ('Cow Milk', 90.0::numeric, 'SWEETS', 126, true),
  ('Buffalo Milk', 120.0::numeric, 'SWEETS', 127, true),
  ('Shahi Jilepi', 20.0::numeric, 'SWEETS', 128, true),
  ('Aam Dahi 100 Gm', 25.0::numeric, 'SWEETS', 129, true),
  ('Dry Fruit Laddu', 45.0::numeric, 'SWEETS', 130, true),
  ('Loose Paneer', 550.0::numeric, 'SWEETS', 131, true),
  ('Masala Lassi', 30.0::numeric, 'SWEETS', 132, true),
  ('Khoa Anarkali', 25.0::numeric, 'SWEETS', 133, true),
  ('Khoa Anarkali Kg', 900.0::numeric, 'SWEETS', 134, true),
  ('Mawa Magic', 25.0::numeric, 'SWEETS', 135, true),
  ('Mawa Magic Kg', 900.0::numeric, 'SWEETS', 136, true),
  ('Special Misti Dahi', 120.0::numeric, 'SWEETS', 137, true),
  ('Mango Malai', 25.0::numeric, 'SWEETS', 138, true),
  ('Nutty Mawa Apple', 25.0::numeric, 'SWEETS', 139, true),
  ('Silver Delight', 25.0::numeric, 'SWEETS', 140, true),
  ('Dry Sweets - Piece', 25.0::numeric, 'SWEETS', 141, true),
  ('Dry Sweets - Kg', 900.0::numeric, 'SWEETS', 142, true),
  ('Badam Burfi', 18.0::numeric, 'SWEETS', 143, true),
  ('Sandesh 20', 20.0::numeric, 'SWEETS', 144, true),
  ('Malpoa', 25.0::numeric, 'SWEETS', 145, true),
  ('Choco Delight', 15.0::numeric, 'SWEETS', 146, true),
  ('Doodh Puli', 12.0::numeric, 'SWEETS', 147, true),
  ('Baked Makha Sandesh', 160.0::numeric, 'SWEETS', 148, true),
  ('Baked Pantooa', 65.0::numeric, 'SWEETS', 149, true),
  ('Kheer Bati', 65.0::numeric, 'SWEETS', 150, true),
  ('Mohan Bhog', 20.0::numeric, 'SWEETS', 151, true),
  ('Plain Curd 500g', 90.0::numeric, 'SWEETS', 152, true),
  ('Balushahi', 18.0::numeric, 'SWEETS', 153, true),
  ('Rajbhog', 20.0::numeric, 'SWEETS', 154, true),
  ('Makha Sandesh Big', 100.0::numeric, 'SWEETS', 155, true),
  ('Makha Sandesh Small', 60.0::numeric, 'SWEETS', 156, true),
  ('Special Laddu', 25.0::numeric, 'SWEETS', 157, true),
  ('Plain Curd 250 Gm', 45.0::numeric, 'SWEETS', 158, true),
  ('Kaju Katli', 20.0::numeric, 'SWEETS', 159, true),
  ('Mishti Dahi 250 Gm', 55.0::numeric, 'SWEETS', 160, true),
  ('Khir Kadam', 20.0::numeric, 'SWEETS', 161, true),
  ('Cream Kalojam', 20.0::numeric, 'SWEETS', 162, true),
  ('Snehadhonyo', 35.0::numeric, 'SWEETS', 163, true),
  ('Jamai Bhogh', 30.0::numeric, 'SWEETS', 164, true),
  ('Mawa Burfi', 15.0::numeric, 'SWEETS', 165, true),
  ('Desi Ghee Laddu', 18.0::numeric, 'SWEETS', 166, true),
  ('Amritti', 12.0::numeric, 'SWEETS', 167, true),
  ('Chana Poda', 700.0::numeric, 'SWEETS', 168, true),
  ('Two In One Rasogolla', 20.0::numeric, 'SWEETS', 169, true),
  ('Kheer Roll', 15.0::numeric, 'SWEETS', 170, true),
  ('Kheer Cocoa Roll', 20.0::numeric, 'SWEETS', 171, true),
  ('Kheer Kutlet', 20.0::numeric, 'SWEETS', 172, true),
  ('Jagannath Khaja', 15.0::numeric, 'SWEETS', 173, true),
  ('Jibe Gaja', 12.0::numeric, 'SWEETS', 174, true),
  ('Baked Mihidana', 50.0::numeric, 'SWEETS', 175, true),
  ('Kaju Katli Kg', 600.0::numeric, 'SWEETS', 176, true),
  ('Kheer Mohan', 20.0::numeric, 'SWEETS', 177, true),
  ('Dilkhush', 20.0::numeric, 'SWEETS', 178, true),
  ('Plain Sandesh', 12.0::numeric, 'SWEETS', 179, true),
  ('Dalgona Sandesh', 40.0::numeric, 'SWEETS', 180, true),
  ('Madhu Chakkar', 20.0::numeric, 'SWEETS', 181, true),
  ('Tripti Sandesh', 18.0::numeric, 'SWEETS', 182, true),
  ('Chocolate Malai Roll', 25.0::numeric, 'SWEETS', 183, true),
  ('Jhinuk Sandesh', 18.0::numeric, 'SWEETS', 184, true),
  ('Taler Bara', 8.33::numeric, 'SWEETS', 185, true),
  ('Singara', 12.0::numeric, 'SNACKS', 186, true),
  ('Aamchur Nimki', 55.0::numeric, 'SNACKS', 187, true),
  ('Vegetable Chop', 12.0::numeric, 'SNACKS', 188, true),
  ('Cheese Veg Corn Sandwich', 65.0::numeric, 'SNACKS', 189, true),
  ('Extra Cheese Slice', 15.0::numeric, 'SNACKS', 190, true),
  ('Special Veg Cheese Corn', 80.0::numeric, 'SNACKS', 191, true),
  ('Veg Corn Sandwich', 50.0::numeric, 'SNACKS', 192, true),
  ('Swornim Chicken Sandwich', 100.0::numeric, 'SNACKS', 193, true),
  ('Swornim Veg Burger', 75.0::numeric, 'SNACKS', 194, true),
  ('Veg Momo (6 Ps)', 60.0::numeric, 'SNACKS', 195, true),
  ('Veg Supreme Momo ( 6 Ps)', 75.0::numeric, 'SNACKS', 196, true),
  ('Chicken Momo', 75.0::numeric, 'SNACKS', 197, true),
  ('Chicken Kurkure Momo', 85.0::numeric, 'SNACKS', 198, true),
  ('Container', 5.0::numeric, 'SNACKS', 199, true),
  ('Raj Chips', 70.0::numeric, 'SNACKS', 200, true),
  ('Chicken Cheese Bun', 40.0::numeric, 'SNACKS', 201, true),
  ('Chicken Patties', 40.0::numeric, 'SNACKS', 202, true),
  ('Paneer Patties', 35.0::numeric, 'SNACKS', 203, true),
  ('Corn Spinach Patties', 35.0::numeric, 'SNACKS', 204, true),
  ('Paneer Bun', 35.0::numeric, 'SNACKS', 205, true),
  ('Dahi Vada Full', 100.0::numeric, 'SNACKS', 206, true),
  ('Dahi Vada Half', 60.0::numeric, 'SNACKS', 207, true),
  ('Paneer Tikka Garlic Bread', 100.0::numeric, 'SNACKS', 208, true),
  ('Dal Puri & Curry', 45.0::numeric, 'SNACKS', 209, true),
  ('Extra Curry', 5.0::numeric, 'SNACKS', 210, true),
  ('Extra Dal Puri', 15.0::numeric, 'SNACKS', 211, true),
  ('Raita', 15.0::numeric, 'SNACKS', 212, true),
  ('Fried Channa Masala', 60.0::numeric, 'SNACKS', 213, true),
  ('Jalapeno Cheese Garlic Bread', 100.0::numeric, 'SNACKS', 214, true),
  ('Paneer Devil', 15.0::numeric, 'SNACKS', 215, true),
  ('Paneer Tikka Gbread Half', 60.0::numeric, 'SNACKS', 216, true),
  ('Khasta Nimki', 10.0::numeric, 'SNACKS', 217, true),
  ('Idli/sambar Vara 1pc', 20.0::numeric, 'SNACKS', 218, true),
  ('Idli /sambar Vara 3pcs', 60.0::numeric, 'SNACKS', 219, true),
  ('Idli / Sambar Vara 4pcs', 75.0::numeric, 'SNACKS', 220, true),
  ('Bread Pakora', 12.5::numeric, 'SNACKS', 221, true),
  ('Dhokhla Plate', 50.0::numeric, 'SNACKS', 222, true),
  ('Makhana', 239.0::numeric, 'SNACKS', 223, true),
  ('Dhokla 1 Pice', 17.0::numeric, 'SNACKS', 224, true),
  ('Swornim Chicken Burger', 100.0::numeric, 'SNACKS', 225, true),
  ('Chicken Burger', 85.0::numeric, 'SWORNIM SAVORIES', 226, true),
  ('Chicken Cheese Patties', 40.0::numeric, 'SWORNIM SAVORIES', 227, true),
  ('Egg Patties', 35.0::numeric, 'SWORNIM SAVORIES', 228, true),
  ('Veg Patties', 30.0::numeric, 'SWORNIM SAVORIES', 229, true),
  ('Chicken Hot Dog.', 45.0::numeric, 'SWORNIM SAVORIES', 230, true),
  ('Chicken Burger.', 40.0::numeric, 'SWORNIM SAVORIES', 231, true),
  ('Paneer Hot Dog', 40.0::numeric, 'SWORNIM SAVORIES', 232, true),
  ('Chicken Masala Puff', 30.0::numeric, 'SWORNIM SAVORIES', 233, true),
  ('Veg Puff', 25.0::numeric, 'SWORNIM SAVORIES', 234, true),
  ('Egg Puff', 25.0::numeric, 'SWORNIM SAVORIES', 235, true),
  ('Chicken Danish', 60.0::numeric, 'SWORNIM SAVORIES', 236, true),
  ('Chilli Chicken Roll', 50.0::numeric, 'SWORNIM SAVORIES', 237, true),
  ('Chicken Supreme', 65.0::numeric, 'SWORNIM SAVORIES', 238, true),
  ('Chicken Internet.', 50.0::numeric, 'SWORNIM SAVORIES', 239, true),
  ('Paneer Puff.', 45.0::numeric, 'SWORNIM SAVORIES', 240, true),
  ('Chicken Kulcha Roll', 60.0::numeric, 'SWORNIM SAVORIES', 241, true),
  ('Spinach & Mushroom Puff', 40.0::numeric, 'SWORNIM SAVORIES', 242, true),
  ('Chicken Tandoor Roll', 65.0::numeric, 'SWORNIM SAVORIES', 243, true),
  ('Paneer Kulcha Roll', 60.0::numeric, 'SWORNIM SAVORIES', 244, true),
  ('Chicken Hotdog (patty)', 30.0::numeric, 'SWORNIM SAVORIES', 245, true),
  ('Chicken Roll', 50.0::numeric, 'SWORNIM SAVORIES', 246, true),
  ('Chicken Hotdog', 50.0::numeric, 'SWORNIM SAVORIES', 247, true),
  ('Chicken & Cheese Finger', 60.0::numeric, 'SWORNIM SAVORIES', 248, true),
  ('Corn Cheese Bucket', 35.0::numeric, 'SWORNIM SAVORIES', 249, true),
  ('Chicken & Cheese Puff', 65.0::numeric, 'SWORNIM SAVORIES', 250, true),
  ('Tandoori Chicken Puff', 45.0::numeric, 'SWORNIM SAVORIES', 251, true),
  ('Mirchi Chicken Puff', 45.0::numeric, 'SWORNIM SAVORIES', 252, true),
  ('Chilli Chicken Puff.', 50.0::numeric, 'SWORNIM SAVORIES', 253, true),
  ('Chilli Paneer Roll', 50.0::numeric, 'SWORNIM SAVORIES', 254, true),
  ('Chicken Samosa', 35.0::numeric, 'SWORNIM SAVORIES', 255, true),
  ('Potato Cheese Ball', 40.0::numeric, 'SWORNIM SAVORIES', 256, true),
  ('Chilli Cheese Toast', 35.0::numeric, 'SWORNIM SAVORIES', 257, true),
  ('Paneer Pizza', 50.0::numeric, 'SWORNIM SAVORIES', 258, true),
  ('Chicken Pizza', 50.0::numeric, 'SWORNIM SAVORIES', 259, true),
  ('Cheese Chicken Roll', 60.0::numeric, 'SWORNIM SAVORIES', 260, true),
  ('Chicken Cheese Roll', 60.0::numeric, 'SWORNIM SAVORIES', 261, true),
  ('Chicken Parcel', 55.0::numeric, 'SWORNIM SAVORIES', 262, true),
  ('Momo Hotdog', 55.0::numeric, 'SWORNIM SAVORIES', 263, true),
  ('Chicken Plate', 60.0::numeric, 'SWORNIM SAVORIES', 264, true),
  ('Chicken Pao', 35.0::numeric, 'SWORNIM SAVORIES', 265, true),
  ('Chicken Sausage', 55.0::numeric, 'SWORNIM SAVORIES', 266, true),
  ('Egg Cheese Bun', 40.0::numeric, 'SWORNIM SAVORIES', 267, true),
  ('Cheesy Chicken Busket', 40.0::numeric, 'SWORNIM SAVORIES', 268, true),
  ('Choco Mousse', 40.0::numeric, 'SWORNIM COOKIES & OTHERS', 269, true),
  ('Muffin', 15.0::numeric, 'SWORNIM COOKIES & OTHERS', 270, true),
  ('Mudpie', 45.0::numeric, 'SWORNIM COOKIES & OTHERS', 271, true),
  ('Tiramisu', 45.0::numeric, 'SWORNIM COOKIES & OTHERS', 272, true),
  ('Fruit Cake.', 25.0::numeric, 'SWORNIM COOKIES & OTHERS', 273, true),
  ('Masala Bread', 45.0::numeric, 'SWORNIM COOKIES & OTHERS', 274, true),
  ('Cheese Garlic Bread', 50.0::numeric, 'SWORNIM COOKIES & OTHERS', 275, true),
  ('Dali Gaja', 65.0::numeric, 'SWORNIM COOKIES & OTHERS', 276, true),
  ('Cheese Straw', 70.0::numeric, 'SWORNIM COOKIES & OTHERS', 277, true),
  ('Masala Khari', 50.0::numeric, 'SWORNIM COOKIES & OTHERS', 278, true),
  ('Sweet Khari', 50.0::numeric, 'SWORNIM COOKIES & OTHERS', 279, true),
  ('Butterfly Biscuit', 70.0::numeric, 'SWORNIM COOKIES & OTHERS', 280, true),
  ('Honey Oatmeal Cookie', 80.0::numeric, 'SWORNIM COOKIES & OTHERS', 281, true),
  ('Butter Cookie', 80.0::numeric, 'SWORNIM COOKIES & OTHERS', 282, true),
  ('Jeera Cookie', 70.0::numeric, 'SWORNIM COOKIES & OTHERS', 283, true),
  ('Almond Cookie', 80.0::numeric, 'SWORNIM COOKIES & OTHERS', 284, true),
  ('Choco Fudge Brownie', 80.0::numeric, 'SWORNIM COOKIES & OTHERS', 285, true),
  ('Red Velvet Brownie', 80.0::numeric, 'SWORNIM COOKIES & OTHERS', 286, true),
  ('Vanilla Muffin.', 40.0::numeric, 'SWORNIM COOKIES & OTHERS', 287, true),
  ('Chocochip Muffin', 40.0::numeric, 'SWORNIM COOKIES & OTHERS', 288, true),
  ('Red Velvet Muffin', 40.0::numeric, 'SWORNIM COOKIES & OTHERS', 289, true),
  ('Double Chocolate Muffin', 40.0::numeric, 'SWORNIM COOKIES & OTHERS', 290, true),
  ('Blueberry Muffin.', 40.0::numeric, 'SWORNIM COOKIES & OTHERS', 291, true),
  ('Plain Bread', 45.0::numeric, 'SWORNIM COOKIES & OTHERS', 292, true),
  ('Multigrain Bread.', 60.0::numeric, 'SWORNIM COOKIES & OTHERS', 293, true),
  ('Kulcha Sweet Bun', 25.0::numeric, 'SWORNIM COOKIES & OTHERS', 294, true),
  ('Plain Khari', 50.0::numeric, 'SWORNIM COOKIES & OTHERS', 295, true),
  ('Swornim Coconut Cookies', 70.0::numeric, 'SWORNIM COOKIES & OTHERS', 296, true),
  ('Chocochips Muffin', null::numeric, 'SWORNIM COOKIES & OTHERS', 297, true),
  ('Frozen Green Peas 500 Gm', null::numeric, 'SAFAL PRODUCTS', 298, true),
  ('Frozen Sweet Corn 200 Gm', null::numeric, 'SAFAL PRODUCTS', 299, true),
  ('Green Peas 200 Gm', null::numeric, 'SAFAL PRODUCTS', 300, true),
  ('French Fries 400 Gm', null::numeric, 'SAFAL PRODUCTS', 301, true),
  ('Cappuccino Coffee', 30.0::numeric, 'TEA & COFFEE', 302, true),
  ('Espresso Coffee', 25.0::numeric, 'TEA & COFFEE', 303, true),
  ('Assam Tea With Milk', 20.0::numeric, 'TEA & COFFEE', 304, true),
  ('Assam Tea Without Milk', 15.0::numeric, 'TEA & COFFEE', 305, true),
  ('Lemon Tea', 15.0::numeric, 'TEA & COFFEE', 306, true),
  ('Ginger Tea', 20.0::numeric, 'TEA & COFFEE', 307, true),
  ('Choco Lava', 50.0::numeric, 'SWORNIM PASTRIES', 308, true),
  ('Chocolate Doughnuts', 50.0::numeric, 'SWORNIM PASTRIES', 309, true),
  ('Red Velvet Cheese Pastry', 50.0::numeric, 'SWORNIM PASTRIES', 310, true),
  ('Chocolate Truffle 15%', 50.0::numeric, 'SWORNIM PASTRIES', 311, true),
  ('Choco Chips', 40.0::numeric, 'SWORNIM PASTRIES', 312, true),
  ('Choco Balls', 25.0::numeric, 'SWORNIM PASTRIES', 313, true),
  ('Butterscotch Pastry.', 40.0::numeric, 'SWORNIM PASTRIES', 314, true),
  ('Oreo Mousse', 50.0::numeric, 'SWORNIM PASTRIES', 315, true),
  ('Vanilla Pastry', 35.0::numeric, 'SWORNIM PASTRIES', 316, true),
  ('Strawberry Delight', 35.0::numeric, 'SWORNIM PASTRIES', 317, true),
  ('Chocolate Cream Roll', 35.0::numeric, 'SWORNIM PASTRIES', 318, true),
  ('Vanilla Cream Roll', 35.0::numeric, 'SWORNIM PASTRIES', 319, true),
  ('Blueberry Cheese Pastry', 50.0::numeric, 'SWORNIM PASTRIES', 320, true),
  ('Red Velvet Cake 1 Lb', 500.0::numeric, 'SWORNIM PASTRIES', 321, true),
  ('Red Velvet Cheese Cake', 450.0::numeric, 'SWORNIM PASTRIES', 322, true),
  ('Black Forest Cake.', 475.0::numeric, 'SWORNIM PASTRIES', 323, true),
  ('Butterscotch Cake.', 400.0::numeric, 'SWORNIM PASTRIES', 324, true),
  ('Korean Bun', 45.0::numeric, 'SWORNIM PASTRIES', 325, true),
  ('Red Velvet Korean Bun', 55.0::numeric, 'SWORNIM PASTRIES', 326, true),
  ('Vitamin C', 40.0::numeric, 'SWORNIM PASTRIES', 327, true),
  ('Alovera Juice 20', 20.0::numeric, 'BEVERAGES', 328, true),
  ('A●l oVveegr a Juice 30', 30.0::numeric, 'BEVERAGES', 329, true),
  ('Geks Juice 20', 20.0::numeric, 'BEVERAGES', 330, true),
  ('Strawberry Milkshake', 25.0::numeric, 'BEVERAGES', 331, true),
  ('Choco Milkshake', 30.0::numeric, 'BEVERAGES', 332, true),
  ('Iced Coffee', 30.0::numeric, 'BEVERAGES', 333, true),
  ('Lassi Red Cow', 20.0::numeric, 'BEVERAGES', 334, true),
  ('Lemoni', 12.0::numeric, 'BEVERAGES', 335, true),
  ('●Ke Vsaerg Milkshake', 25.0::numeric, 'BEVERAGES', 336, true),
  ('Badam Milkshake', 25.0::numeric, 'BEVERAGES', 337, true),
  ('Mango Milkshake', 25.0::numeric, 'BEVERAGES', 338, true),
  ('Fantasy', 5.0::numeric, 'BEVERAGES', 339, true),
  ('Truffle Small', 150.0::numeric, 'BEVERAGES', 340, true),
  ('Truffle Love', 240.0::numeric, 'CHOCOLATE', 341, true),
  ('Truffle Guiter', 240.0::numeric, 'CHOCOLATE', 342, true),
  ('Marshmallow', 25.0::numeric, 'CHOCOLATE', 343, true),
  ('Truffle Chocolate', 5.0::numeric, 'CHOCOLATE', 344, true),
  ('Truffle Love Mini', 90.0::numeric, 'CHOCOLATE', 345, true),
  ('Truffle Love Small', 150.0::numeric, 'CHOCOLATE', 346, true),
  ('Marshmallow Big', 40.0::numeric, 'CHOCOLATE', 347, true),
  ('Truffle Selection', 175.0::numeric, 'CHOCOLATE', 348, true),
  ('Lollipop', 10.0::numeric, 'CHOCOLATE', 349, true);